export const adminSeed = {
  username: 'Veloura Admin',
  email: 'admin@veloura-lighting.com',
  password: 'VelouraAdmin2026!',
  role: 'admin',
};

export const collectionsSeed = [
  {
    name: 'Grand Chandeliers',
    slug: 'grand-chandeliers',
    eyebrow: '01 / STATEMENT ELEGANCE',
    tagline: 'Timeless elegance in every crystal.',
    description: 'Sculptural centrepieces designed to command the room without overwhelming it. Crafted with optical-grade crystal and hand-finished brushed brass.',
    heroImage: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1400&q=85',
    category: 'Chandeliers',
    features: [
      'Hand-blown Czech crystal elements',
      'Custom drop lengths available',
      'Precision 2700K warm LED illumination',
      'Integrated DALI / 0-10V dimming',
    ],
    materials: 'Solid Brushed Brass, Hand-Cut Lead-Free Crystal, Anodized Aluminum',
    applications: 'Grand foyers, double-height living rooms, formal dining halls, luxury hotel lobbies',
    featured: true,
    order: 1,
    isActive: true,
  },
  {
    name: 'Architectural Pendants',
    slug: 'architectural-pendants',
    eyebrow: '02 / MODERN GEOMETRY',
    tagline: 'Sculptural forms. Refined spaces.',
    description: 'Precise linear and geometric suspension lights engineered for contemporary architectural spaces, dining islands, and executive suites.',
    heroImage: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1400&q=85',
    category: 'Pendants',
    features: [
      'Direct/indirect glare-controlled optics',
      'Ultra-slim micro canopy',
      'High CRI 97+ color rendering',
      'Bespoke length configurations up to 4 meters',
    ],
    materials: 'Extruded Aluminum, Frosted Quartz Diffusers, Champagne Anodized Steel',
    applications: 'Dining tables, kitchen islands, conference suites, reception desks',
    featured: true,
    order: 2,
    isActive: true,
  },
  {
    name: 'Smart Ambient Systems',
    slug: 'smart-ambient-systems',
    eyebrow: '03 / INTELLIGENT LIVING',
    tagline: 'Intelligent lighting for modern living.',
    description: 'Concealed, layered architectural lighting systems that adapt dynamically to circadian rhythms, interior scenes, and architectural contours.',
    heroImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85',
    category: 'Ambient Systems',
    features: [
      'Seamless cove and plaster-in profiles',
      'Tunable white spectrum (2200K - 5000K)',
      'Native Lutron, Control4 & KNX integration',
      'Zero flicker digital driver technology',
    ],
    materials: 'Architectural Plaster-In Channels, High-Density LED Matrix, PMMA Diffusers',
    applications: 'Whole-home scene control, luxury corridors, wellness rooms, art galleries',
    featured: true,
    order: 3,
    isActive: true,
  },
  {
    name: 'Wall Lighting',
    slug: 'wall-lighting',
    eyebrow: '04 / QUIET DETAIL',
    tagline: 'Architectural sconces that accentuate texture and form.',
    description: 'Low-profile architectural sconces designed to wash vertical surfaces with warm, glare-free light, creating depth and subtle drama.',
    heroImage: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1400&q=85',
    category: 'Wall Lighting',
    features: [
      'Dual up/down indirect optics',
      'Hand-finished metallic patinas',
      'IP44 splash-rated options available',
      'Magnetic mounting plates',
    ],
    materials: 'Hammered Bronze, Honed Travertine, Frosted Glass, Satin Brass',
    applications: 'Hallways, feature stone walls, bedroom headboards, powder rooms',
    featured: false,
    order: 4,
    isActive: true,
  },
  {
    name: 'Floor Lighting',
    slug: 'floor-lighting',
    eyebrow: '05 / SCULPTURAL STANDARDS',
    tagline: 'Freestanding ambient light sculptures.',
    description: 'Freestanding architectural luminaires that double as modern art pieces during the day and cast ambient pools of light by night.',
    heroImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1400&q=85',
    category: 'Floor & Table',
    features: [
      'Weighted solid marble or brass base',
      'Touch capacitive stepping dimmer',
      '360-degree rotational light head',
      'Custom textile cord wraps',
    ],
    materials: 'Nero Marquina Marble, Solid Brass, Hand-Spun Copper, Opal Glass',
    applications: 'Reading nooks, salon corners, lounge suites, gallery rooms',
    featured: false,
    order: 5,
    isActive: true,
  },
  {
    name: 'Custom Solutions',
    slug: 'custom-solutions',
    eyebrow: '06 / MADE FOR YOU',
    tagline: 'Bespoke one-of-one lighting concepts.',
    description: 'Fully bespoke lighting fixtures engineered and crafted specifically around your architect’s vision, ceiling scale, and interior design concept.',
    heroImage: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=85',
    category: 'Bespoke',
    features: [
      'Full 3D CAD modeling & optical simulation',
      'Physical mockups & finish samples',
      'Dedicated lighting engineering team',
      'Global white-glove installation support',
    ],
    materials: 'Any custom metals, hand-blown glass, stone, or specialized alloys',
    applications: 'Bespoke super-yachts, private palaces, flagship luxury retail, penthouses',
    featured: false,
    order: 6,
    isActive: true,
  },
];

export const productsSeed = [
  {
    name: 'The Aurelia',
    slug: 'the-aurelia',
    category: 'Grand Chandelier',
    collectionSlug: 'grand-chandeliers',
    image: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1400&q=85',
    description: 'A cascading crystal composition with a contemporary silhouette, engineered to create mesmerizing ambient light play across grand interiors.',
    specifications: 'Diameter: 1400mm | Drop: 2200mm | Weight: 48kg | 2700K Warm White | 120W LED',
    materials: 'Solid Brass, Optical Czech Crystal',
    finish: 'Brushed Satin Brass',
    dimensions: 'Dia: 1400mm x H: 2200mm',
    colorTemperature: '2700K',
    wattage: '120W',
    ipRating: 'IP20',
    featured: true,
    order: 1,
    isActive: true,
  },
  {
    name: 'The Orion',
    slug: 'the-orion',
    category: 'Pendant Light',
    collectionSlug: 'architectural-pendants',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1400&q=85',
    description: 'Geometric floating pendants featuring champagne-anodized aluminum and micro-prismatic optics for glare-free dining illumination.',
    specifications: 'Length: 1800mm | Height: 320mm | Suspension: Up to 3000mm | 2700K CRI 97',
    materials: 'Extruded Champagne Aluminum, Quartz Diffusers',
    finish: 'Champagne Anodized',
    dimensions: 'L: 1800mm x W: 120mm x H: 320mm',
    colorTemperature: '2700K',
    wattage: '65W',
    ipRating: 'IP20',
    featured: true,
    order: 2,
    isActive: true,
  },
  {
    name: 'The Halo',
    slug: 'the-halo',
    category: 'Wall Light',
    collectionSlug: 'wall-lighting',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85',
    description: 'A minimalist circular wall sconce emitting a warm back-lit halo effect against textured marble or plaster walls.',
    specifications: 'Diameter: 450mm | Depth: 55mm | 18W LED | Phase/DALI Dimmable | IP20',
    materials: 'Hand-Hammered Bronze, Satin Brass Ring',
    finish: 'Antique Bronze & Satin Gold',
    dimensions: 'Dia: 450mm x D: 55mm',
    colorTemperature: '2700K',
    wattage: '18W',
    ipRating: 'IP44',
    featured: true,
    order: 3,
    isActive: true,
  },
  {
    name: 'The Élan',
    slug: 'the-elan',
    category: 'Table Light',
    collectionSlug: 'floor-lighting',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1400&q=85',
    description: 'A sculptural table luminaire balancing a solid brass sphere on a honed black travertine pillar with integrated touch control.',
    specifications: 'Height: 520mm | Base: 140x140mm | Touch Dimmer | 2700K Soft Glow',
    materials: 'Nero Marquina Marble, Solid Spun Brass, Opal Glass',
    finish: 'Honed Black Marble & Polished Brass',
    dimensions: 'H: 520mm x Base: 140x140mm',
    colorTemperature: '2700K',
    wattage: '12W',
    ipRating: 'IP20',
    featured: true,
    order: 4,
    isActive: true,
  },
];

export const projectsSeed = [
  {
    title: 'PRIVATE RESIDENCE',
    slug: 'private-residence-dubai',
    location: 'Emirates Hills, Dubai, UAE',
    country: 'UAE',
    category: 'Residential',
    year: '2025',
    coverImage: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85',
    description: 'Layered architectural lighting for a 2,500 sq. m contemporary villa in Emirates Hills. Features custom ceiling coves, smart circadian scenes, and a bespoke 4-meter entry chandelier.',
    scope: 'Interior Lighting Design, Custom Chandelier Fabrication, Smart Controls Commissioning',
    featured: true,
    order: 1,
    isActive: true,
  },
  {
    title: 'THE GRAND HOTEL',
    slug: 'the-grand-hotel-doha',
    location: 'West Bay, Doha, Qatar',
    country: 'Qatar',
    category: 'Hospitality',
    year: '2025',
    coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=85',
    description: 'A warm, cinematic lighting scheme for an elevated 5-star hotel lobby, spa, and presidential suites, balancing rich architectural shadows with warm champagne accents.',
    scope: 'Architectural Lighting Specification, Lobby Statement Fixtures, Facade Illumination',
    featured: true,
    order: 2,
    isActive: true,
  },
  {
    title: 'LUXURY VILLA',
    slug: 'luxury-villa-abu-dhabi',
    location: 'Saadiyat Island, Abu Dhabi, UAE',
    country: 'UAE',
    category: 'Residential',
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85',
    description: 'Integrated ambient lighting that follows the sweeping curved ceiling contours of a beachfront residence on Saadiyat Island.',
    scope: 'Plaster-in Linear Cove Lighting, Decorative Pendants, Landscape & Poolside Ambient',
    featured: true,
    order: 3,
    isActive: true,
  },
  {
    title: 'FINE DINING RESTAURANT',
    slug: 'fine-dining-restaurant-dubai',
    location: 'DIFC, Dubai, UAE',
    country: 'UAE',
    category: 'Restaurant',
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1400&q=85',
    description: 'Intimate, low-glare atmospheric lighting designed to focus warmth onto table settings while maintaining soft, mystery-filled peripheral ambient light.',
    scope: 'Table-Focused Micro Spotlights, Acoustic Pendant Systems, Wine Cellar Lighting',
    featured: true,
    order: 4,
    isActive: true,
  },
  {
    title: 'ROYAL COMMERCIAL TOWER',
    slug: 'royal-commercial-tower-riyadh',
    location: 'KAFD, Riyadh, Saudi Arabia',
    country: 'Saudi Arabia',
    category: 'Commercial',
    year: '2025',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=85',
    description: 'Precision architectural lighting for a corporate headquarters atrium, featuring automated dynamic daylight integration.',
    scope: 'Atrium Suspended Light Matrix, Energy Efficient Daylight Harvesting, DALI-2 Control',
    featured: false,
    order: 5,
    isActive: true,
  },
];

export const faqsSeed = [
  {
    question: 'What types of architectural lighting does Veloura offer?',
    answer: 'Veloura specializes in luxury chandeliers, architectural pendants, concealed smart ambient cove systems, low-profile wall sconces, and fully bespoke custom lighting concepts for high-end residential and commercial spaces.',
    category: 'General',
    order: 1,
    isActive: true,
  },
  {
    question: 'Do you provide custom lighting solutions for private villas and hotels?',
    answer: 'Yes, our lighting architects and master craftsmen engineer bespoke one-of-one lighting fixtures tailored to unique room ceiling scales, architectural geometry, and interior design briefs across Dubai, Abu Dhabi, Doha, and globally.',
    category: 'Bespoke Design',
    order: 2,
    isActive: true,
  },
  {
    question: 'Does Veloura provide lighting consultation services in Dubai & UAE?',
    answer: 'We provide end-to-end lighting consultations in Dubai and the UAE. Our team reviews room blueprints, natural light orientation, material finishes, photometrics, and smart lighting scene controls.',
    category: 'Consultation',
    order: 3,
    isActive: true,
  },
  {
    question: 'Are your lighting systems compatible with Lutron, KNX, or DALI controls?',
    answer: 'All Veloura fixtures and ambient systems integrate seamlessly with major smart automation standards including DALI-2, Lutron HomeWorks, Control4, and KNX digital dimming controllers.',
    category: 'Smart Systems',
    order: 4,
    isActive: true,
  },
];
